name: Bandit SAST Scan
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install bandit
      - run: bandit -r . -f json -o bandit-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
